version: '3.8'
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached

  redis:
    image: redis:latest
    restart: unless-stopped
    network_mode: service:workspace
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    restart: unless-stopped
    network_mode: service:workspace
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
