global:
  scrape_interval: 15s
  scrape_timeout: 15s
scrape_configs:
  - job_name: "Tsubaki"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus:32098"]
